### ISSUE TITLE
Pop!_OS 21.10 Application Drawer and Dock are mixed with pop-dark theme

### ISSUE THREAD

**Issue by SirNikOdTW** [dracula/gtk#166]
Using the dracula gtk theme for the shell mixes up the dracula theme and the standard pop-dark theme as you can see in the screenshots below. I know that may be a cosmic thing and this you may not support because System76 moved further away from gnome-shell or whatever the problem is but at least it's documented here.

## Dock:
![image](https://user-images.githubusercontent.com/39330220/147395731-99b86c50-6c68-4e70-9e98-78ebf271b880.png)
The background looks like the dracula themed one but the standard pop-dark bar covers it.

## Application Drawer:
![app_drawer](https://user-images.githubusercontent.com/39330220/147395762-d6d035cd-d459-440e-9622-b2313b83ac14.png)
*how it actual looks*
Here the elements (search input field and selected folder) are dracula themed, the rest not. Also the individual widgets are not as supposed to be (with spaces between and indicators; look at the differences between the should-be and actual screenshots).
Here a screenshot how it should look:
![app_drawer_should_be](https://user-images.githubusercontent.com/39330220/147395837-8716c25c-4a77-4e5e-8ac1-3f599debd38f.png)*how it is supposed to looks*
(The missing folder icons you can ignore i think, that must be an icon-theme related problem)

## Time and date in the topbar:
![image](https://user-images.githubusercontent.com/39330220/147395767-1c7caf7b-a78e-482b-bc56-0e53e8728d0b.png)
Here you can see that there are two highlights by hovering

**Comment by shabby-goddess** [comment]
Having the same issue with Fedora on Gnome 41. So, I don't think this issue is specific to Pop OS.

**Comment by EliverLara** [comment]
@shabby-goddess your issue seems  to be you're using the wrong shell theme version, please take a look to #124

**Comment by shabby-goddess** [comment]
@EliverLara oh, right. Thanks for the help.

**Comment by piotrowskiadam** [comment]
@EliverLara Thanks, It fixes double highlighting, However the new application drawer is still not implemented in Dracula theme right?

**Comment by marabesi** [comment]
I don't know if this is related, but all the menus (when clicking on the time or the battery) don't keep the same dark theme as the system: 

![Screenshot from 2022-02-13 21-14-06](https://user-images.githubusercontent.com/2129872/153773057-b238dc8e-57af-484c-acd5-2b0764ab94b0.png)

**Comment by piotrowskiadam** [comment]
@marabesi It's not related.

First you have to enable user themes by installing this extension
https://extensions.gnome.org/extension/19/user-themes/

Then in Gnome tweaks app you should be able to change Shell to Dracula (not only Applications):
![image](https://user-images.githubusercontent.com/55131509/153775267-1fa09b34-5c1c-488d-9f0e-b438ce559f13.png)

As I remember in the tweaks app it will use the name of the folder of your theme so it's good to rename it to Dracula.

**Comment by marabesi** [comment]
@piotrowskiadam thanks for the heads up, did what you suggested and it's fixed now 🙌

**Comment by pasan93** [comment]
@SirNikOdTW There's a workaround to make it a little better. But it's not a complete fix.

You can keep _"pop-dark"_ as the shell theme. Then disable _"cosmic dock"_ and _"cosmic workspaces"_ in "Extensions".
After that, install _"Floating Dock"_ 
https://extensions.gnome.org/extension/3730/floating-dock/

Finally, install "_Transparent Topbar"_
https://extensions.gnome.org/extension/1765/transparent-topbar/


Then it should look like this. 

![dock](https://user-images.githubusercontent.com/29046066/155888503-49e73f7d-a78b-4c6b-ab7e-8fe4692eaad7.png)
![Topbar](https://user-images.githubusercontent.com/29046066/155888514-63883c90-3e55-4f65-9632-131a8f98d5b1.png)


It's not perfect but it's better than the overlapping dock. 

Hope this will help. :)

**Comment by pasan93** [comment]
@SirNikOdTW  There's a workaround to make it a little better. But it's not a complete fix.

You can keep _"pop-dark"_ as the shell theme. Then disable _"cosmic dock"_ and _"cosmic workspaces"_ in _"Extensions"._
After that, install _"Floating Dock"_ 
https://extensions.gnome.org/extension/3730/floating-dock/

_***cosmic workspaces** seems to malfunction with the suggested fix._ So you can simply use the native gnome workspace. 


Finally, install "_Transparent Topbar"_
https://extensions.gnome.org/extension/1765/transparent-topbar/


Then it should look like this. 

![dock](https://user-images.githubusercontent.com/29046066/155888503-49e73f7d-a78b-4c6b-ab7e-8fe4692eaad7.png)
![Topbar](https://user-images.githubusercontent.com/29046066/155888514-63883c90-3e55-4f65-9632-131a8f98d5b1.png)


It's not perfect but it's better than the overlapping dock. 

Hope this will help 😃

**Comment by pasan93** [comment]
@SirNikOdTW 
This is working. 

https://github.com/dracula/gtk/issues/124

**Comment by SirNikOdTW** [comment]
> @SirNikOdTW This is working.
> 
> #124

Yes, I tried it when Eliver came up with it earlier. It fixes the weird border look od the cosmic launcher and the double layered dock.

What's still missing: 
- dracula color scheme applied to the launcher and dock
- In the launcher there are still the weird looking app indicators (blurry points at the bottom of each launcher entry)

**Comment by pasan93** [comment]
> > @SirNikOdTW This is working.
> > #124
> 
> Yes, I tried it when Eliver came up with it earlier. It fixes:
> 
> * the weird border look of the cosmic launcher
> * the double layered dock.
> * the double highlighting of the date/time
> 
> What's still missing:
> 
> * dracula color scheme applied to the launcher and dock
> * In the launcher there are still the weird looking app indicators (blurry points at the bottom of each launcher entry)

I see. I was using a hybrid of "pop-dark" and "dracula" for sometime. (Shell theme as pop-dark"). Tbh, I didn't notice the launcher entry issue.

**Comment by exiele** [comment]
On manjaro gnome, #124 fix the dock and panel but menus are still not matching the theme:
![image](https://user-images.githubusercontent.com/20567069/200546646-69398277-aa1d-4885-83f8-8a7ab822db5f.png)
